services:
  - type: web
    name: makola-spices
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
